# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
    toxify:
        docker:
            - image: cimg/python:3.10.1

        steps:
            - checkout
            - run: pip install tox
            - run: tox

            - store_artifacts:
                  path: ./screenshots
                  destination: screenshots-file

            - store_artifacts:
                  path: ./log
                  destination: logs-file

workflows:
    version: 2
    myproj:
        jobs:
            - toxify
# orbs:
#     python: circleci/python@1.5.0

# workflows:
#     mainwf:
#         jobs:
#             - python/test:
#                   args: "--ignore-pipfile --dev --python 3.8"
#                   pkg-manager: pipenv
#                   test-tool: pytest
#                   version: "3.9"
